"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importStar(require("react"));
const store_1 = require("../store");
const lucide_react_1 = require("lucide-react");
const uuid_1 = require("uuid");
const AIGenerator = () => {
    const { setCurrentRegimen, regimens, setRegimens } = (0, store_1.useRegimenStore)();
    const [isGenerating, setIsGenerating] = (0, react_1.useState)(false);
    const [inputType, setInputType] = (0, react_1.useState)('pdf');
    const handleGenerate = () => {
        setIsGenerating(true);
        // Simulate AI generation delay
        setTimeout(() => {
            const generatedRegimen = {
                schema_version: '1.0',
                app_version: '1.0.0',
                regimen_id: (0, uuid_1.v4)(),
                created_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
                regimen_core: {
                    regimen_name: 'AI生成レジメン（サンプル）',
                    cancer_type: '胃癌',
                    treatment_purpose: '術後補助化学療法',
                    inpatient_outpatient: '外来',
                    interval_days: 21,
                    reference_sources: 'Generated by AI assistant',
                    courses: []
                },
                regimen_support_info: {
                    basic_info: 'AIによって生成された情報です。適宜修正してください。',
                    indications: '', contraindications: '', start_criteria: '', stop_criteria: '', dose_reduction: '', adverse_effects_and_management: '', references: ''
                }
            };
            setRegimens([...regimens, generatedRegimen]);
            setCurrentRegimen(generatedRegimen);
            setIsGenerating(false);
            alert('AI生成が完了しました（シミュレーション）');
        }, 2000);
    };
    return ((0, jsx_runtime_1.jsxs)("div", { className: "card bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-200", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 mb-6 text-blue-800 font-bold", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Sparkles, { size: 20, className: "text-yellow-500 fill-yellow-500" }), (0, jsx_runtime_1.jsx)("h3", { children: "AI\u30EC\u30B8\u30E1\u30F3\u81EA\u52D5\u751F\u6210" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-3 gap-3 mb-6", children: [(0, jsx_runtime_1.jsxs)("button", { className: `flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${inputType === 'pdf' ? 'bg-white border-blue-500 shadow-sm' : 'bg-transparent border-slate-200 opacity-60'}`, onClick: () => setInputType('pdf'), children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Upload, { size: 24 }), (0, jsx_runtime_1.jsx)("span", { className: "text-xs font-bold", children: "PDF\u30A2\u30C3\u30D7\u30ED\u30FC\u30C9" })] }), (0, jsx_runtime_1.jsxs)("button", { className: `flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${inputType === 'online' ? 'bg-white border-blue-500 shadow-sm' : 'bg-transparent border-slate-200 opacity-60'}`, onClick: () => setInputType('online'), children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Globe, { size: 24 }), (0, jsx_runtime_1.jsx)("span", { className: "text-xs font-bold", children: "\u30AA\u30F3\u30E9\u30A4\u30F3\u53D6\u5F97" })] }), (0, jsx_runtime_1.jsxs)("button", { className: `flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${inputType === 'manual' ? 'bg-white border-blue-500 shadow-sm' : 'bg-transparent border-slate-200 opacity-60'}`, onClick: () => setInputType('manual'), children: [(0, jsx_runtime_1.jsx)(lucide_react_1.FileText, { size: 24 }), (0, jsx_runtime_1.jsx)("span", { className: "text-xs font-bold", children: "\u624B\u5165\u529B\u88DC\u52A9" })] })] }), (0, jsx_runtime_1.jsx)("button", { className: "btn btn-primary w-full py-4 text-lg shadow-lg disabled:opacity-50", onClick: handleGenerate, disabled: isGenerating, children: isGenerating ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Loader2, { className: "animate-spin" }), " \u89E3\u6790\u4E2D..."] })) : ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: "AI\u3067\u30EC\u30B8\u30E1\u30F3\u3092\u69CB\u7BC9\u3059\u308B" })) }), (0, jsx_runtime_1.jsx)("p", { className: "mt-4 text-[10px] text-slate-400 text-center", children: "\u203B\u30D7\u30ED\u30C8\u30BF\u30A4\u30D7\u7248\u3067\u306F\u30B7\u30DF\u30E5\u30EC\u30FC\u30B7\u30E7\u30F3\u52D5\u4F5C\u3068\u306A\u308A\u307E\u3059\u3002" })] }));
};
exports.default = AIGenerator;
//# sourceMappingURL=AIGenerator.js.map