import React, { useState } from 'react';
import { useRegimenStore } from '../store';
import { Sparkles, Upload, Globe, FileText, Loader2 } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';

const AIGenerator: React.FC = () => {
  const { setCurrentRegimen, regimens, setRegimens } = useRegimenStore();
  const [isGenerating, setIsGenerating] = useState(false);
  const [inputType, setInputType] = useState<'pdf' | 'online' | 'manual'>('pdf');
  const [files, setFiles] = useState<File[]>([]);
  const [url, setUrl] = useState('');
  const [text, setText] = useState('');

  const handleGenerate = () => {
    if (inputType === 'pdf' && files.length === 0) {
      alert('PDFファイルを選択してください。');
      return;
    }
    if (inputType === 'online' && !url) {
      alert('URLを入力してください。');
      return;
    }
    if (inputType === 'manual' && !text) {
      alert('テキストを入力してください。');
      return;
    }

    setIsGenerating(true);
    // Simulate AI generation delay
    setTimeout(() => {
      const generatedRegimen = {
        schema_version: '1.0',
        app_version: '1.0.0',
        regimen_id: uuidv4(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        regimen_core: {
          regimen_name: 'AI生成レジメン（サンプル）',
          cancer_type: '胃癌',
          treatment_purpose: '術後補助化学療法',
          inpatient_outpatient: '外来',
          interval_days: 21,
          reference_sources: 'Generated by AI assistant',
          courses: []
        },
        regimen_support_info: {
          basic_info: 'AIによって生成された情報です。適宜修正してください。',
          indications: '', contraindications: '', start_criteria: '', stop_criteria: '', dose_reduction: '', adverse_effects_and_management: '', references: ''
        }
      };
      setRegimens([...regimens, generatedRegimen]);
      setCurrentRegimen(generatedRegimen);
      setIsGenerating(false);
      alert('AI生成が完了しました（シミュレーション）');
    }, 2000);
  };

  return (
    <div className="card bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-200">
      <div className="flex items-center gap-2 mb-6 text-blue-800 font-bold">
        <Sparkles size={20} className="text-yellow-500 fill-yellow-500" />
        <h3>AIレジメン自動生成</h3>
      </div>

      <div className="grid grid-cols-3 gap-3 mb-6">
        <button 
          className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${inputType === 'pdf' ? 'bg-white border-blue-500 shadow-sm' : 'bg-transparent border-slate-200 opacity-60'}`}
          onClick={() => setInputType('pdf')}
        >
          <Upload size={24} />
          <span className="text-xs font-bold">PDFアップロード</span>
        </button>
        <button 
           className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${inputType === 'online' ? 'bg-white border-blue-500 shadow-sm' : 'bg-transparent border-slate-200 opacity-60'}`}
          onClick={() => setInputType('online')}
        >
          <Globe size={24} />
          <span className="text-xs font-bold">オンライン取得</span>
        </button>
        <button 
           className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${inputType === 'manual' ? 'bg-white border-blue-500 shadow-sm' : 'bg-transparent border-slate-200 opacity-60'}`}
          onClick={() => setInputType('manual')}
        >
          <FileText size={24} />
          <span className="text-xs font-bold">手入力補助</span>
        </button>
      </div>

      <div className="mb-6 bg-white p-4 rounded-xl border border-blue-100 min-h-[120px] flex items-center justify-center">
        {inputType === 'pdf' && (
          <div className="flex flex-col gap-3 w-full">
            <span className="text-sm font-bold text-slate-700">プロトコルやガイドラインのPDFを選択（複数選択可）</span>
            <input 
              type="file" 
              accept=".pdf" 
              multiple
              className="input text-sm p-3 border-dashed border-2 cursor-pointer
                         file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 
                         file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
              onChange={(e) => setFiles(Array.from(e.target.files || []))}
            />
            {files.length > 0 && (
              <div className="text-xs text-slate-500">
                {files.length} ファイル選択中
              </div>
            )}
          </div>
        )}
        {inputType === 'online' && (
          <div className="flex flex-col gap-3 w-full">
            <span className="text-sm font-bold text-slate-700">ガイドライン等のWebページのURL</span>
            <input 
              type="url" 
              className="input text-base" 
              placeholder="https://..."
              value={url}
              onChange={(e) => setUrl(e.target.value)}
            />
          </div>
        )}
        {inputType === 'manual' && (
          <div className="flex flex-col gap-3 w-full">
            <span className="text-sm font-bold text-slate-700">レジメンのテキスト（薬剤名、用量など）</span>
            <textarea 
              className="input min-h-[100px] text-sm" 
              placeholder="例: パクリタキセル 80mg/m2 day1,8,15..."
              value={text}
              onChange={(e) => setText(e.target.value)}
            />
          </div>
        )}
      </div>

      <button 
        className="btn btn-primary w-full py-4 text-lg shadow-lg disabled:opacity-50"
        onClick={handleGenerate}
        disabled={isGenerating}
      >
        {isGenerating ? (
          <>
            <Loader2 className="animate-spin" /> 解析中...
          </>
        ) : (
          <>AIでレジメンを構築する</>
        )}
      </button>
      <p className="mt-4 text-[10px] text-slate-400 text-center">
        ※プロトタイプ版ではシミュレーション動作となります。
      </p>
    </div>
  );
};

export default AIGenerator;
