"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const store_1 = require("../store");
const lucide_react_1 = require("lucide-react");
const types_1 = require("../types");
const ItemEditor = ({ courseId, groupId, items }) => {
    const { addItem, deleteItem, updateItem } = (0, store_1.useRegimenStore)();
    const handleUpdate = (itemId, updates) => {
        updateItem(courseId, groupId, itemId, updates);
    };
    const doseUnits = ['mg/kg', 'mg/m2', 'mg/body', 'AUC', 'units/m²', 'IU/m²', 'IU/kg', '手入力'];
    const methods = ['経口', '静注', '点滴', '皮下注', '筋注', '髄注'];
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [items.map((item) => ((0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-12 gap-3 p-3 bg-slate-50/50 rounded-lg border border-slate-100 relative group/item", children: [(0, jsx_runtime_1.jsxs)("div", { className: "col-span-4", children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-[10px] uppercase font-bold text-slate-400 mb-1", children: "\u85AC\u5264\u540D (\u4E00\u822C\u540D\u30FB\u5546\u54C1\u540D)" }), (0, jsx_runtime_1.jsx)("input", { type: "text", className: "input text-sm", value: item.drug_name_display, onChange: (e) => handleUpdate(item.item_id, { drug_name_display: e.target.value }), placeholder: "\u30EA\u30C4\u30AD\u30B7\u30DE\u30D6 (\u30EA\u30C4\u30AD\u30B5\u30F3)" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "col-span-2", children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-[10px] uppercase font-bold text-slate-400 mb-1", children: "\u6295\u4E0E\u65B9\u6CD5" }), (0, jsx_runtime_1.jsx)("select", { className: "input text-sm", value: item.administration_method, onChange: (e) => handleUpdate(item.item_id, { administration_method: e.target.value }), children: methods.map(m => (0, jsx_runtime_1.jsx)("option", { value: m, children: m }, m)) })] }), (0, jsx_runtime_1.jsxs)("div", { className: "col-span-2", children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-[10px] uppercase font-bold text-slate-400 mb-1", children: "\u7528\u91CF" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-1", children: [(0, jsx_runtime_1.jsx)("input", { type: "text", className: "input text-sm flex-1", value: item.dose, onChange: (e) => handleUpdate(item.item_id, { dose: e.target.value }), placeholder: "375" }), (0, jsx_runtime_1.jsx)("select", { className: "input text-xs w-20 px-1", value: item.dose_unit, onChange: (e) => handleUpdate(item.item_id, { dose_unit: e.target.value }), children: doseUnits.map(u => (0, jsx_runtime_1.jsx)("option", { value: u, children: u }, u)) })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "col-span-3", children: [(0, jsx_runtime_1.jsx)("label", { className: "block text-[10px] uppercase font-bold text-slate-400 mb-1", children: "\u6295\u4E0E\u65E5 (Day)" }), (0, jsx_runtime_1.jsx)("input", { type: "text", className: "input text-sm", value: item.schedule.excel_display_hint || '', onChange: (e) => handleUpdate(item.item_id, {
                                    schedule: { ...item.schedule, excel_display_hint: e.target.value }
                                }), placeholder: "Day 1, 8, 15" })] }), (0, jsx_runtime_1.jsx)("div", { className: "col-span-1 flex items-end justify-center", children: (0, jsx_runtime_1.jsx)("button", { className: "p-2 text-slate-300 hover:text-red-500 transition-colors", onClick: () => deleteItem(courseId, groupId, item.item_id), children: (0, jsx_runtime_1.jsx)(lucide_react_1.Trash2, { size: 16 }) }) }), (0, jsx_runtime_1.jsxs)("div", { className: "col-span-12 grid grid-cols-3 gap-3", children: [(0, jsx_runtime_1.jsx)("input", { type: "text", className: "input text-xs bg-white/50", value: item.base_solution || '', onChange: (e) => handleUpdate(item.item_id, { base_solution: e.target.value }), placeholder: "\u5E0C\u91C8\u6DB2 (\u4F8B: \u751F\u98DF500mL)" }), (0, jsx_runtime_1.jsx)("input", { type: "text", className: "input text-xs bg-white/50", value: item.infusion_rate || '', onChange: (e) => handleUpdate(item.item_id, { infusion_rate: e.target.value }), placeholder: "\u901F\u5EA6 (\u4F8B: 90\u5206)" }), (0, jsx_runtime_1.jsx)("input", { type: "text", className: "input text-xs bg-white/50", value: item.comments[0]?.text || '', onChange: (e) => handleUpdate(item.item_id, {
                                    comments: [{ comment_type: '任意', text: e.target.value }]
                                }), placeholder: "\u30B3\u30E1\u30F3\u30C8" })] })] }, item.item_id))), (0, jsx_runtime_1.jsxs)("button", { className: "text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1 font-medium", onClick: () => addItem(courseId, groupId), children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { size: 14 }), " \u85AC\u5264\u30FB\u624B\u6280\u3092\u8FFD\u52A0"] })] }));
};
exports.default = ItemEditor;
//# sourceMappingURL=ItemEditor.js.map